project:
  type: website
  output-dir: docs

website:
  title: "Schistosomiasis innovations"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Projects"
        menu:
          - text: "Dams & Disease"
            href: dams_and_disease.qmd
          - text: "Risk assessment software"
            href: invest_schisto_tool.qmd
          - text: "Snail habitat AI toolset"
            href: snail_habitat_toolset.qmd
          - text: "Rice & Fish"
            href: rice_fish_schisto.qmd
      - text: "De Leo Lab"
        href: "https://deleolab.stanford.edu/"
        target: _blank
      - text: "Stanford | DECO"
        href: "https://hph.stanford.edu/focal_areas/deco"
        target: _blank
  back-to-top-navigation: true
  page-footer:
      left: 
        - text: "Â© 2025 De Leo Lab"
      center: 
        - text: "Contact Us"
          icon: envelope
          href: mailto:kmkauffm@stanford.edu
      right: 
        - text: "Stanford University"
      background: "#8C1515" # Background color for the footer
      foreground: "#ffffff" # Text color for the footer
      
format:
  html:
    theme: journal
    css: styles.css
    toc: true
    linkcolor: "#620e0e"
    link-external-newwindow: true



